In [4]:
"""
https://www.youtube.com/watch?v=QUT1VHiLmmI
https://github.com/KeithGalli/NumPy/blob/master/NumPy%20Tutorial.ipynb
"""

"""
View docstring - Add '?' after command
np.random.randint?
"""

import numpy as np

In [7]:
# Initialize array

a = np.array([1,2,3])
print(a)

[1 2 3]


In [13]:
# Get information about array

# Get Dimension
a.ndim

# Get Shape
a.shape

# Get type 
a.dtype

# Get Size
a.itemsize

# Get Total Size
a.nbytes
a.size


3

In [15]:
# Accessing/Changing Specific Elements, rows columns, etc

b = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])

# Get specific element [row, column]
b[1,5]

# Get specific row
b[0, :]

# Get specific column
b[:, 0]

# [startIdx:endIdx:stepSize]
b[0, 1:-1:2]

# replace element(s)
a[1,5] = 20
a[:,2] = 15

# Returns the index of a value
np.index()

# argwhere finds an index
np.argWhere(np.arange(5))[1][1]

array([2, 4, 6])

In [17]:
# Initializing Different Types of Arrays

# All 0s matrix
np.zeros((2,3))

# All 1s (ones) matrix
# (num of arrays, rows, columns)
np.ones((4,2,2), dtype='int32')

# Random decimal numbers
np.random.rand(4,2) # decimal
np.random.sample(a.shape)
np.random.randint(-4,8, size=(3,3)) # integer
np.random.permutation(np.range(10)) # shuffles

# The identity matrix
np.identity(5)

# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

# Creates an array to a certain range (Generator in reg. py)
# (startIdx, endIdx, step)
np.arange(100)

# changes the shape of output
np.reshape()

# rounds values
np.round(0)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [20]:
"""
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
"""

output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [24]:
# Copying array
# do deep copy (copy()) instead of copying the reference
c = b
d = b.copy()

In [25]:
# Math routines (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

In [ ]:
# Load data from file to numpy

"""
# Generate numpy array from text file
np.genfromtext('filename.txt', delimiter=',') 
"""